name: Deployment pipeline
run-name: Build, deploy and e2e test ${{github.ref_name}}

permissions:
  contents: read  # This is required for actions/checkout
  id-token: write  # This is required for authenticating with aws

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cnb_build:
    name: Build
    uses: ./.github/workflows/package.yml
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      CI_AWS_ACCOUNT: ${{ secrets.CI_AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}

  run_e2e_tests_docker_compose:
    name: Run E2E tests against docker compose
    uses: ./.github/workflows/run_e2e_tests_docker_compose.yml
    secrets:
      PULLPREVIEW_GOVUK_NOTIFY_API_KEY: ${{ secrets.PULLPREVIEW_GOVUK_NOTIFY_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}

  deploy_test:
    name: Deploy to test
    needs:
      - cnb_build
    uses: ./.github/workflows/deploy.yml
    concurrency:
      group: fs-deploy-test
      cancel-in-progress: false
    with:
      environment: test
      run_e2e_tests: true
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      CI_AWS_ACCOUNT: ${{ secrets.CI_AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}
      SERVICE_ACCOUNT_USERNAME: ${{ secrets.SERVICE_ACCOUNT_USERNAME }}
      SERVICE_ACCOUNT_PASSWORD: ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}
      FS_BASIC_AUTH_USERNAME: ${{ secrets.FS_BASIC_AUTH_USERNAME }}
      FS_BASIC_AUTH_PASSWORD: ${{ secrets.FS_BASIC_AUTH_PASSWORD }}

  deploy_prod:
    name: Deploy to prod
    needs:
      - deploy_test
    uses: ./.github/workflows/deploy.yml
    concurrency:
      group: fs-deploy-prod
      cancel-in-progress: false
    with:
      environment: prod
      run_e2e_tests: false
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      CI_AWS_ACCOUNT: ${{ secrets.CI_AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}
      SERVICE_ACCOUNT_USERNAME: ${{ secrets.SERVICE_ACCOUNT_USERNAME }}
      SERVICE_ACCOUNT_PASSWORD: ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}
